name: immortalwrt-builder

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否开启 SSH 调试'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: v25.12.1
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: 准备源码
      uses: actions/checkout@main


    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/*
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force

        sudo -E apt-get update

        sudo -E apt-get install -y \
        build-essential \
        clang \
        flex \
        bison \
        g++ \
        gawk \
        gcc-multilib \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python3 \
        python3-pyelftools \
        rsync \
        unzip \
        wget \
        curl \
        zlib1g-dev \
        file \
        ccache

        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean

        sudo timedatectl set-timezone "$TZ"


    - name: 下载 ImmortalWrt 源码
      run: |
        git clone --depth=1 \
        -b $REPO_BRANCH \
        $REPO_URL \
        openwrt


    - name: 缓存编译
      uses: actions/cache@v4
      with:
        path: |
          openwrt/.ccache
          openwrt/dl
        key: |
          ${{ runner.os }}-immortalwrt-${{ env.REPO_BRANCH }}-${{ hashFiles('**/diy-part*.sh','.config') }}

        restore-keys: |
          ${{ runner.os }}-immortalwrt-${{ env.REPO_BRANCH }}-


    - name: 更新 feeds
      run: |

        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf

        chmod +x $DIY_P1_SH

        cd openwrt

        $GITHUB_WORKSPACE/$DIY_P1_SH

        ./scripts/feeds update -a

        ./scripts/feeds install -a


    - name: 配置固件
      run: |

        cd openwrt


        curl -L \
        https://immortalwrt.kyarucloud.moe/releases/25.12.1/targets/x86/64/config.buildinfo \
        -o .config


        if [ -e $GITHUB_WORKSPACE/$CONFIG_FILE ];then

        cat $GITHUB_WORKSPACE/$CONFIG_FILE >> .config

        fi


        chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH

        $GITHUB_WORKSPACE/$DIY_P2_SH


        echo "CONFIG_CCACHE=y" >> .config


        make defconfig



    - name: SSH调试
      uses: P3TERX/ssh2actions@v1.0.0

      if: |
        github.event.inputs.ssh == 'true'

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}



    - name: 下载源码包
      run: |

        cd openwrt

        make download -j16

        find dl -size -1024c -exec rm -f {} \;



    - name: 编译固件
      run: |

        cd openwrt

        export CCACHE_DIR=$PWD/.ccache

        ccache -M 5G


        make -j$(nproc) || make -j1 V=s


        echo "status=success" >> $GITHUB_OUTPUT

        echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV


        grep '^CONFIG_TARGET.*DEVICE.*=y' .config \
        | sed -r 's/.*DEVICE_(.*)=y/\1/' \
        > DEVICE_NAME



    - name: 整理固件
      run: |

        cd openwrt/bin/targets/*/*

        rm -rf packages

        echo "FIRMWARE=$PWD" >> $GITHUB_ENV



    - name: 上传固件
      uses: actions/upload-artifact@main

      with:

        name: ImmortalWrt-${{ env.DATE }}

        path: ${{ env.FIRMWARE }}



    - name: 发布 Release
      uses: softprops/action-gh-release@v2

      if: env.UPLOAD_RELEASE == 'true'

      with:

        tag_name: Build_${{ env.DATE }}

        body: |
          ImmortalWrt ${{ env.REPO_BRANCH }}
          
          x86/64
          
          Argon
          
          TurboACC

        files: |
          ${{ env.FIRMWARE }}/*



    - name: 清理旧记录
      uses: Mattraks/delete-workflow-runs@main

      with:

        retain_days: 3
        keep_minimum_runs: 3
